export const LOAD_PODCASTS_STARTED = 'LOAD_PODCASTS_STARTED';
export const LOAD_PODCASTS_SUCCESS = 'LOAD_PODCASTS_SUCCESS';
export const LOAD_PODCASTS_ERROR = 'LOAD_PODCASTS_ERROR';

export const LOAD_PODCASTENTRIES_STARTED = 'LOAD_PODCASTENTRIES_STARTED';
export const LOAD_PODCASTENTRIES_SUCCESS = 'LOAD_PODCASTENTRIES_SUCCESS';
export const LOAD_PODCASTENTRIES_ERROR = 'LOAD_PODCASTENTRIES_ERROR';

export const ADD_PODCASTENTRY_STARTED = 'ADD_PODCASTENTRY_STARTED';
export const ADD_PODCASTENTRY_SUCCESS = 'ADD_PODCASTENTRY_SUCCESS';
export const ADD_PODCASTENTRY_ERROR = 'ADD_PODCASTENTRY_ERROR';

export const LOAD_PROFILE_STARTED = 'LOAD_PROFILE_STARTED';
export const LOAD_PROFILE_SUCCESS = 'LOAD_PROFILE_SUCCESS';
export const LOAD_PROFILE_ERROR = 'LOAD_PROFILE_ERROR';

export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_REQUIRED = 'LOGIN_REQUIRED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGGEDIN = 'LOGGEDIN';
export const LOGOUT_STARTED = 'LOGOUT_STARTED';
export const LOGOUT_COMPLETE = 'LOGOUT_COMPLETE';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export const LOGIN_INIT_STARTED = 'LOGIN_INIT_STARTED';
export const LOGIN_INIT_SUCCESS = 'LOGIN_INIT_SUCCESS';
export const LOGIN_INIT_FAILED = 'LOGIN_INIT_FAILED';
