name: Build Android and iOS
on:
    push:
        branches:
            - trunk
jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install yarn dependencies
              run: |
                  yarn install

    build-android:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install
            - name: Build Android Release
              run: |
                  cd android && ./gradlew assembleRelease -PODNOMS_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' -PODNOMS_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}'
              env:
                PODNOMS_UPLOAD_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}

            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: app-release.apk
                  path: android/app/build/outputs/apk/release/
