name: Build Android and iOS
on:
    push:
        branches:
            - trunk
jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install yarn dependencies
              run: |
                  yarn install

    build-android:
        needs: install
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install npm dependencies
              run: |
                  npm install
            # - name: Setup tmate session
            #   env:
            #       RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
            #       PODNOMS_UPLOAD_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
            #   uses: mxschmitt/action-tmate@v3

            - name: Build Android Release
              env:
                  RELEASE_KEYSTORE: ${{ secrets.RELEASE_KEYSTORE }}
                  PODNOMS_UPLOAD_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
              run: |
                  echo "$RELEASE_KEYSTORE" > release.keystore.asc
                  gpg -d --passphrase "$PODNOMS_UPLOAD_STORE_PASSWORD" --batch release.keystore.asc > android/app/podnoms.keystore
                  cd android && ./gradlew assembleRelease

            - name: Upload Artifact
              uses: actions/upload-artifact@v1
              with:
                  name: app-release.apk
                  path: android/app/build/outputs/apk/release/
